version: "3.3"
services:

  celeryworker:
    volumes:
      - ./backend/app:/work/app

  backend:
    ports:
      - "80:80"
    volumes:
      - ./backend/app:/work/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    command: dev

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/app/src/
    command: start
