name: Continuous Deployment
run-name: Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  Push-docker-images:
    runs-on: ubuntu-latest
    name: Push docker images
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Push docker images on docker hub
        run: make push
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

