name: Continuous Deployment
run-name: Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Push docker images on docker hub
        run: make push
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy website on EC2
        run: make ssh_deploy
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
          FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
