name: Continuous Integration
run-name: Continuous Integration
on: [push]
jobs:
  Check-lint:
    runs-on: ubuntu-latest
    name: Check lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Check lint
        run: make lint
